# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  variable-for-property: 0
  quotes:
    - 2
    -
      style: single

  nesting-depth:
    - 1
    -
      max-depth: 4

  space-after-comma: 2
  space-after-colon: 2
  single-line-per-selector: 2
  empty-line-between-blocks: 2
  trailing-semicolon: 2
  # too buggy to use
  no-mergeable-selectors: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0

  class-name-format:
    - 1
    -
      convention: hyphenatedbem
